bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='bag'),
    path('add/<item_id>', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name="remove_from_bag"),
]

happy_pet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('profile/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
    path('wishlist/', include('wishlist.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "happy_pet.views.page_not_found_view"
handler500 = "happy_pet.views.internal_error_page"

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.all_products, name='products'),
     path('<int:product_id>/', views.product_detail,
          name='product_detail'),
     path('add/', views.add_product, name='add_product'),
     path('edit/<int:product_id>/',
          views.edit_product, name='edit_product'),
     path('delete/<int:product_id>/',
          views.delete_product, name='delete_product'),
     path('orders_overview/',
          views.orders_overview, name='orders_overview'),

]

checkout/models.py
import uuid
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile
from django.db import models


class Order(models.Model):
    order_number = models.CharField(
        max_length=32, null=False, editable=False)

    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='orders')

    full_name = models.CharField(
        max_length=50, null=False, blank=False)

    email = models.EmailField(
        max_length=254, null=False, blank=False)

    phone_number = models.CharField(
        max_length=20, null=False, blank=False)

    country = CountryField(
        blank_label="Country *", null=False, blank=False)

    postcode = models.CharField(
        max_length=20, null=True, blank=True)

    town_or_city = models.CharField(
        max_length=40, null=False, blank=False)

    street_address1 = models.CharField(
        max_length=80, null=False, blank=False)

    street_address2 = models.CharField(
        max_length=80, null=True, blank=True)

    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)

    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)

    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)

    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        self.order_total = self.lineitems.aggregate(
                Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total *
                settings.STANDARD_DELIVERY_PERCENTAGE/100)
        else:
            self.delivery_cost = 0

        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number if
        it has not been set already
        """

        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False,
        on_delete=models.CASCADE)
    product_size = models.CharField(max_length=10, null=True, blank=True)
    product_color = models.CharField(max_length=15, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.FloatField(
        blank=False, null=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number if
        it has not been set already
        """

        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User


class Category(models.Model):
    category_id = models.IntegerField(
        db_column='category_ID',
        primary_key=True)

    name = models.CharField(max_length=45)

    friendlyname = models.CharField(
        db_column='friendlyName',
        max_length=45, blank=True, null=True)

    class Meta:
        db_table = 'category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendlyname


class Product(models.Model):
    small = 'Small'
    medium = 'Medium'
    large = 'Large'
    x_large = 'X-large'

    red = 'red'
    pink = 'Pink'
    green = 'Green'
    blue = 'Blue'
    grey = 'Grey'
    black = 'Black'
    white = 'White'
    brown = 'Brown'

    has_sizes = [
        (small, 'Small'),
        (medium, 'Medium'),
        (large, 'Large'),
        (x_large, 'X-large'),
    ]

    colors = [
        (red, 'Red'),
        (pink, 'Pink'),
        (green, 'Green'),
        (blue, 'Blue'),
        (grey, 'Grey'),
        (black, 'Black'),
        (white, 'White'),
        (brown, 'Brown')
    ]

    product_id = models.AutoField(
        db_column='Product_ID', primary_key=True)

    name = models.CharField(max_length=45)
    friendlyname = models.CharField(
        db_column='friendlyName', max_length=45)

    category = models.ForeignKey(
        'Category', models.DO_NOTHING, db_column='category_ID')

    subcategory = models.ForeignKey(
        'Subcategories', models.DO_NOTHING, db_column='subcategory_ID')

    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, blank=True, null=True)

    image1 = models.ImageField(blank=True, null=True)
    image2 = models.ImageField(blank=True, null=True)
    image3 = models.ImageField(blank=True, null=True)
    sku = models.CharField(unique=True, max_length=254)
    has_sizes = MultiSelectField(
        max_length=350, choices=has_sizes, blank=True, null=True)
    colors = MultiSelectField(
        max_length=350, choices=colors, blank=True, null=True)

    class Meta:
        db_table = 'Products'

    def __str__(self):
        return self.name

    def CategoryName(self):
        return self.category.name

    def SubCategoryName(self):
        return self.subcategory.name


class Subcategories(models.Model):

    dogs = 'dogs'
    cats = 'cats'
    birds = 'birds'
    rodents = 'rodents'

    categories = [
        (dogs, 'dogs'),
        (cats, 'cats'),
        (birds, 'birds'),
        (rodents, 'rodents'),
    ]

    subcategory_id = models.AutoField(
        db_column='subcategory_ID', primary_key=True)
    name = models.CharField(max_length=45)
    friendly_name = models.CharField(max_length=45, blank=True, null=True)
    category = MultiSelectField(
        max_length=350, choices=categories, blank=True, null=True)

    class Meta:
        db_table = 'SUBCATEGORIES'
        verbose_name_plural = 'Subcategories'

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    product = models.ForeignKey(
        Product, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='reviews', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    stars = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

products/forms.py
from django import forms
from .models import Product, ProductReview, Subcategories, Category
from .widgets import CustomClearableFileInput


class ProductReviewForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        fields = ('content', 'stars',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'content': 'Write your review here',
            'stars': 'Rate',
        }

        self.fields['content'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if self.fields[field].required:
                placeholder = f'{placeholders[field]} *'
            else:
                placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'product-review-form'
            self.fields[field].label = False


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    image1 = forms.ImageField(
        label='Image1', required=False, widget=CustomClearableFileInput)

    image2 = forms.ImageField(
        label='Image2', required=False, widget=CustomClearableFileInput)

    image3 = forms.ImageField(
        label='Image3', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        subcategories = Subcategories.objects.all()
        category_name = [(
            c.category_id, c.name) for c in categories]

        subcategories_name = [(
            s.subcategory_id, s.name) for s in subcategories]

        self.fields['category'].choices = category_name
        self.fields['subcategory'].choices = subcategories_name

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-3 my-2'

products/views.py
from django.shortcuts import (
    get_object_or_404, redirect, render, reverse)
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower

from .models import Product, Category, Subcategories
from .forms import ProductForm
from checkout.models import Order


def all_products(request):
    """ A view to return all products """
    products = Product.objects.all().order_by('name')
    query = None
    categories = None
    subcategories = None
    sort = None
    direction = None
    related_subcategory = None

    if request.GET:
        if 'sort' and 'direction' in request.GET:
            sortkey = request.GET['sort']
            direction = request.GET['direction']

            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))

            if sortkey == 'category':
                sortkey = 'category__name'

            if direction == "desc":
                sortkey = f'-{sortkey}'

            products = products.order_by(sortkey)

        if 'category' and 'subcategory' in request.GET:
            categories = request.GET['category'].split(',')
            subcategories = request.GET['subcategory'].split(',')

            # Gets the related subcategories of the selected
            #  category to pass it as
            # a url param to filter all subcategories
            # of the selected category
            related_subcategory = Subcategories.objects.filter(
                category__icontains=categories[0]).values_list(
                    'name', flat=True)

            products = products.filter(
                category__name__in=categories,
                subcategory__name__in=subcategories)

            categories = Category.objects.filter(name__in=categories)
            subcategories = Subcategories.objects.filter(
                name__in=subcategories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You did not enter any search criteria!")
                return redirect(reverse('products'))

            queries = (
                Q(name__icontains=query) | Q(description__icontains=query) |
                Q(subcategory__friendly_name__icontains=query))
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    template = 'products/products.html'
    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_subcategories': subcategories,
        'current_sorting': current_sorting,
        'related_subcategory': related_subcategory,
    }

    return render(request, template, context)


def product_detail(request, product_id):
    """ A view to return product details and similar products """

    products = Product.objects.all()
    product = get_object_or_404(Product, pk=product_id)
    similar_products = products.filter(
        category=product.category,
        subcategory=product.subcategory).exclude(
        product_id=product.product_id)

    template = 'products/product_detail.html'
    context = {
        'product': product,
        'similar_products': similar_products,
    }

    return render(request, template, context)


@login_required
def add_product(request):
    """
    Add a product to the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            product = form.save()
            messages.success(request, "Successfully added product")
            return redirect(
                reverse('product_detail', args=[product.product_id]))
        else:
            messages.error(request, "Failed to add product.\
                             Please ensure the form is valid.")
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
        'from_product_page': True,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit a product to the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, product_id=product_id)

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully Updated product")
            return redirect(
                reverse('product_detail', args=[product.product_id]))
        else:
            messages.error(request, "Failed to Edit product.\
                                 Please ensure the form is valid.")
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}.')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
        'from_product_page': True,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete a product
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, product_id=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))


@login_required
def orders_overview(request):
    '''
    A view to render all the orders for the store staff
    '''
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    orders = Order.objects.all()
    template = 'products/orders_overview.html'
    context = {
        'orders': orders,
    }

    return render(request, template, context)

products/templates/products/includes/add_product_form.html
<form class="form" action="{% url 'add_to_bag' product.product_id %}" method="POST">
    {% csrf_token %}
    <div class="form-row">
        {% with product.has_sizes as s %}
        {% if s %}
            <div class="col-12">
                <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                    {% for i in s %}
                        <option value="{{ i }}" {% if i == 'Medium' %}selected{% endif %}>{{ i }}</option>
                    {% endfor %}
                </select>
            </div>
        {% endif %}
        {% endwith %}

        {% with product.colors as c %}
        {% if c %}
            <div class="col-12 py-2">
                <select class="form-control rounded-0 w-50" name="product_color" id='id_product_color'>
                    {% for i in c %}
                        <option value="{{ i }}" {% if i == 'black' %}selected{% endif %}>{{ i }}</option>
                    {% endfor %}
                </select>
            </div>
        {% endif %}
        {% endwith %}
        <div class="col{% if s %}-12 mt-2{% endif %}">
            <p class="mt-3"><strong>Quantity:</strong></p>
            <div class="form-group w-50">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <button class="decrement-qty btn btn-black rounded-0"
                            data-item_id="{{ product.product_id }}"
                            id="decrement-qty_{{ product.product_id }}">
                            <span class="icon">
                                <i class="fas fa-minus"></i>
                            </span>
                        </button>
                    </div>
                    <input class="form-control qty_input" type="number" name="quantity" value="1" min="1"
                        max="99" data-item_id="{{ product.product_id }}"
                        id="id_qty_{{ product.product_id }}">
                    <div class="input-group-append">
                        <button class="increment-qty btn btn-black rounded-0"
                            data-item_id="{{ product.product_id }}"
                            id="increment-qty_{{ product.product_id }}">
                            <span class="icon">
                                <i class="fas fa-plus"></i>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 my-5 ">
            <input type="submit" class="btn btn-lg add-to-bag-btn" value="Add to Bag">
            <input type="hidden" name="redirect_url" value="{{ request.path }}">
        </div>
    </div>
</form>

products/templates/products/includes/product_image_carousel.html
<div id="carouselExampleIndicators" class="carousel product-img-carousel slide" data-bs-ride="carousel">
	<div class="carousel-indicators">
		<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
			aria-current="true" aria-label="Slide 1"></button>
		<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
			aria-label="Slide 2"></button>
		{% if product.image3 %}
			<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
				aria-label="Slide 3">
			</button>
		{% endif %}
	</div>
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img src="{{ product.image1.url }}" class="d-block w-100" alt="{{ product.name }}">
		</div>
		<div class="carousel-item">
			<img src="{{ product.image2.url }}" class="d-block w-100" alt="{{ product.name }}">
		</div>
		{% if product.image3 %}
			<div class="carousel-item">
				<img src="{{ product.image3.url }}" class="d-block w-100" alt="{{ product.name }}">
			</div>
		{% endif %}
	</div>
	<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
		data-bs-slide="prev">

		<span aria-hidden="true"><i class="fa-solid fa-chevron-left text-black carousel-control-left-black"></i></span>
		<span class="visually-hidden">Previous</span>
	</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
		data-bs-slide="next">
		<span aria-hidden="true"><i
				class="fa-solid fa-chevron-right text-black carousel-control-right-black"></i></span>
		<span class="visually-hidden">Next</span>
	</button>
</div>

products/templates/products/includes/quantity_input_script.html
<!-- This method is learned from boutique ado project -->
<script>
    function handleDisableEnable(itemId){
        var currentValue = parseInt($(`#id_qty_${itemId}`).val());
        var minusDisabled = currentValue < 2;
        var plusDisabled = currentValue > 98;
        $(`#decrement-qty_${itemId}`).prop('disabled', minusDisabled);
        $(`#increment-qty_${itemId}`).prop('disabled', plusDisabled);
    }

    // Ensure proper enabling / disabling of all inputs on page load
    var allQtyInputs = $('.qty_input');
    for(var i=0; i < allQtyInputs.length; i++){
        var itemId = $(allQtyInputs[i]).data('item_id');
        handleDisableEnable(itemId);
    }

    // check enable / disable every time the input is changed
    $('.qty_input').change(function() {
        var itemId = $(this).data('item_id');
        handleDisableEnable(itemId);
    })
    // Increment quantity
    $('.increment-qty').click(function(e){
        e.preventDefault();
        var closestInput = $(this).closest('.input-group').find('.qty_input')[0];
        var currentValue = parseInt($(closestInput).val());
        $(closestInput).val(currentValue + 1);
        var itemId = $(this).data('item_id');
        handleDisableEnable(itemId);
    })

    // Decrement quantity
    $('.decrement-qty').click(function(e){
        e.preventDefault();
        var closestInput = $(this).closest('.input-group').find('.qty_input')[0];
        var currentValue = parseInt($(closestInput).val());
        $(closestInput).val(currentValue - 1);
        var itemId = $(this).data('item_id');
        handleDisableEnable(itemId);
    })

</script>

products/templates/products/includes/reviews_accordion_item.html
<div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Reviews
        </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
        data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <div class="row">
                {% for review in product.reviews.all %}
                    <div class="col-12">
                        <div class="card w-100">
                            <div class="card-body">
                                <p class="card-title">{{ review.user }}
                                    <span>
                                        {% if review.stars == 1 %}
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        {% elif review.stars == 2 %}
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        {% elif review.stars == 3 %}
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        {% elif review.stars == 4 %}
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star"></i>
                                        {% elif review.stars == 5 %}
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                            <i class="fa fa-star" style="color: #edd605;"></i>
                                        {% else %}
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        {% endif %}
                                    </span>
                                </p>
                                <p class="card-text">{{ review.content }}</p>
                                <small class="card-subtitle text-muted">Date added : {{ review.date }}</small>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <h4>No review</h4>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

products/templates/products/includes/sorting_selector.html
<div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-center justify-content-md-end">
    <div class="sort-select-wrapper">
        <select id="sort-selector"
            class="custom-select w-100 custom-select-sm p-1 rounded-3 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
            <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>
                Sort by...
            </option>
            <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>
                Price (low to high)
            </option>
            <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>
                Price (high to low)
            </option>
            <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>
                Rating (low to high)
            </option>
            <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>
                Rating (high to low)
            </option>
            <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>
                Name (A-Z)
            </option>
            <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>
                Name (Z-A)
            </option>
            <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>
                Category (A-Z)
            </option>
            <option value="category_desc"
                {% if current_sorting == 'category_desc' %}selected{% endif %}>
                Category (Z-A)
            </option>
        </select>
    </div>
</div>